<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Models\Inventory;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Inventory>
 */
class InventoryFactory extends Factory
{
    protected $model = Inventory::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $categories = ['Engine', 'Brakes', 'Electrical', 'Suspension', 'Transmission', 'Filters', 'Oils & Fluids'];
        $suppliers = ['AutoParts Plus', 'ProMechanic Supply', 'Elite Auto Components', 'MasterParts Inc', 'SpeedTech Parts'];
        $locations = ['A1-01', 'A1-02', 'B2-01', 'B2-02', 'C3-01', 'C3-02', 'D4-01', 'D4-02'];

        $partNames = [
            'Brake Pad', 'Oil Filter', 'Air Filter', 'Spark Plug', 'Timing Belt',
            'Water Pump', 'Alternator', 'Battery', 'Radiator', 'Fuel Pump',
            'Oxygen Sensor', 'Catalytic Converter', 'Shock Absorber', 'CV Joint',
        ];

        return [
            // item_id is auto-generated by database as primary key
            'item_name' => fake()->randomElement($partNames),
            'description' => fake()->sentence(),
            'category' => fake()->randomElement($categories),
            'stock' => fake()->numberBetween(0, 100),
            'reorder_level' => fake()->numberBetween(5, 20),
            'unit_price' => fake()->randomFloat(2, 5, 500),
            'supplier' => fake()->randomElement($suppliers),
            'location' => fake()->randomElement($locations),
            'status' => fake()->randomElement(['active', 'inactive']),
        ];
    }

    /**
     * Indicate that the inventory item is low stock.
     */
    public function lowStock(): static
    {
        return $this->state(fn (array $attributes) => [
            'stock' => fake()->numberBetween(0, $attributes['reorder_level']),
        ]);
    }

    /**
     * Indicate that the inventory item is out of stock.
     */
    public function outOfStock(): static
    {
        return $this->state(fn (array $attributes) => [
            'stock' => 0,
        ]);
    }
}
